.TH HASH_DEALLOC 3
.SH NAME
hash_dealloc \- free up entire hash structure
.SH SYNOPSIS
.B #include <hash.h>
.br
.B void hash_dealloc(struct hash *h);
.SH DESCRIPTION
The
.ul 1
hash_dealloc()
function frees the memory of a hash data structure, including all
its internal state.  After calling
.ul 1
hash_dealloc(),
the pointer
.ul 1
h
should no longer be referenced.
.SH SEE ALSO
.BR hash_alloc (3),
.BR hash_insert (3),
.BR hash_delete (3),
.BR hash_lookup (3),
.BR hash_foreach (3),
.BR hash_size (3)
