OUT=build
include ../src/makefile.all
FILES=autoexec.net banner fstab ftpusers group \
	ids inittab less.help libvga.config motd passwd \
	profile rc shadow

build:

clean:

clobber:

install:
	cp $(FILES) $(ROOT)/etc
