.TH ENABLE_DMA 2
.SH NAME
enable_dma \- enable DMA abilities for current process
.SH SYNOPSIS
.B #include <sys/syscall.h>
.br
.B int enable_dma(int channel);
.SH DESCRIPTION
The
.I enable_dma()
system call
changes the behavior of the kernel to permit a server
to operate in a DMA mode.  In particular, the process
is permitted to use the
.I page_wire()
and
.I page_release()
system calls, and messages received using
.I msg_receive()
are mapped into a DMA server's address space
as writable pages, thus permitting programmed I/O
directly into a client's memory.
.SH NOTES
This call is generally useful only to DMA-based I/O servers,
although certain transaction-oriented direct I/O filesystems
might benefit.
.PP
The argument is the DMA channel to be used by a hardware
DMA server.  On architectures where there is no concept of
DMA channels, it may be passed as 0.  On the x86, this argument
is currently unused.
