.TH FORK 2
.SH NAME
fork \- create new process
.SH SYNOPSIS
.B #include <std.h>
.br
.B pid_t fork(void);
.SH DESCRIPTION
The
.I fork()
system call creates a new process, whose initial open
files and virtual address space are a copy of
.I fork()'s
calling process.  It is the single mechanism for creating a
new process under VSTa.
.PP
On return,
.I fork()
returns 0 in the child process, the child's PID in
the parent process, or -1 in the parent process
if the child could not be created.
.PP
It is legal to call
.I fork()
while more than one thread exists under the current
process.  Only a single thread, starting at the address
of the thread which invoked
.I fork(),
will exist in the new
process.
