.TH MSG_CONNECT 2
.SH NAME
msg_connect \- connect to server
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B int msg_connect(port_name pn, int mode);
.SH DESCRIPTION
The
.I msg_connect()
system service connects a client to a server.
.I pn
specifies the server which passed this value
in its call to
.I msg_port().
.PP
.I mode
is passed to the server, and specifies the type
of access requested.  By convention, these bits
are defined in
.B <sys/fs.h>
and include:
.RS
.nf
.B ACC_READ     - Read access
.B ACC_WRITE    - Write access
.B ACC_EXEC     - Execute
.B ACC_CREATE   - Create/truncate
.B ACC_DIR      - Access directory
.B ACC_CHMOD    - Allow changes of mode and ownership
.fi
.RE
.PP
A connection attempt is synchronous; this call will not return
until the server has received the call, processed it, and
responded with either a
.I msg_accept(), msg_err(),
or terminated due to an explicit
.I exit()
or an unhandled event.
