.TH MSG_ACCEPT 2
.SH NAME
msg_accept \- accept a connection from a client
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B int msg_accept(long handle);
.SH DESCRIPTION
The
.I msg_accept()
system service is used by a server to accept an
incoming connection from a client.  After this call,
the client will be able to exchange messages with
the server.
.PP
.I handle
is the value passed in
.I m_sender
field of the
.B MSG_CONNECT
message received by the server on its port
using
.I msg_receive().
