.TH MSG_PORTNAME 2
.SH NAME
msg_portname \- get name associated with port
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B port_name msg_port(port_t p);
.SH DESCRIPTION
The
.I msg_portname()
system service returns the
.I port_name
associated with an open port, suitable for use in
a later call to
.I msg_connect().
It is most often used to find out if two open files
reside on the same "filesystem", that is, under
the same server.
