.TH MSG_REPLY 2
.SH NAME
msg_reply \- answer a message
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B int msg_reply(long sender, struct msg *msg);
.SH DESCRIPTION
.I msg_reply()
is used by a server to answer a request made by a
client using
.I msg_send(),
and received in this server via
.I msg_receive().
.I sender
should be the value taken from the
.I m_sender
field of the received message.  Like
.I msg_send(),
a message with optional segments may be sent back.  Note
that if the client did not specify
.B M_READ,
the segments will be verified, but not actually transferred.
.I m_arg
should be the number of bytes in the reply.
.PP
The client is blocked until this reply is sent.  Thus, servers providing
access to "slow" I/O (keyboards, RS-232) will often record the
.I m_sender
field, and delay the sending of a reply for extended periods of time.
