.TH MSG_DISCONNECT 2
.SH NAME
msg_disconnect \- disconnect a port
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B int msg_disconnect(port_t port);
.SH DESCRIPTION
.I msg_disconnect()
causes a port to close.  When applied to a server's port, each client
will receive an I/O error on their next attempt to use the port.  If the
client already has an I/O outstanding, it will be completed in error
immediately.
.PP
When used by a client, a
.B M_DISCONNECT
message is queued to the server.  The server may clean up any
data structures, but does not need to reply.  The client has already
been disassociated from the port.
