.TH MUNMAP 2
.SH NAME
munmap \- remove object from process address space
.SH SYNOPSIS
.B #include <sys/mman.h>
.br
.B int munmap(void *vaddr, ulong len);
.SH DESCRIPTION
.I munmap()
removes an object previously attached via
.I mmap().
The entire object existing at
.I vaddr
is removed; it is not possible to invalidate individual pages
of an address space object.
