.TH NOTIFY 2
.SH NAME
notify \- send VSTa event string to a target process or thread
.SH SYNOPSIS
.B #include <sys/syscall.h>
.B #include <sys/param.h>
.br
.B int notify(pid_t pid, pid_t thread, char *err);
.SH DESCRIPTION
.I notify()
delivers a VSTa event to the indicated target.  If
.I pid
is 0, the current process is affected.  If
.I thread
is 0, all threads in the target process are affected.
Finally, if
.I thread
is -1, all processes associated with the given
process group are affected.
.PP
The string specified, which can be up to EVLEN characters
in length, is sent to each target.  If the process has
an event handler, it will be invoked; see
.I notify_handler().
Otherwise, the target will terminate.  The unique string "kill"
can not be caught; it always causes termination.
.SH NOTES
The
.I notify()
system call wrapper actually counts up the length of
the event string, and passes this count in to the actual
kernel interface.
