.TH PAGE_RELEASE 2
.SH NAME
page_release \- unlock wired memory
.SH SYNOPSIS
.B #include <sys/syscall.h>
.br
.B int page_release(uint handle);
.SH DESCRIPTION
The
.I page_release()
system call
unlocks memory previously locked down by
.I page_wire().
The
.I handle
is the return value from such a previous call;
the corresponding page is made available for paging.
