.TH CLONE 2
.SH NAME
clone \- create new distinct client connection copied from old
.SH SYNOPSIS
.B #include <sys/syscall.h>
.br
.B int clone(port_t port);
.SH DESCRIPTION
.I clone()
creates a new connection to the server currently serving
.I port.
After a successful
.I clone,
the client will have a new connection, whose initial
file position, access rights, etcetera, reflect those of
the original
.I port.
However, future changes to position and such will be unique
to each
.I port_t,
as no connection exists after the completion of the
.I clone.
.SH NOTES
The
.I clone()
system call resembles much more the POSIX treatment
of file descriptors in a
.I fork()
than the semantics of a POSIX
.I dup().
