.TH ENABLE_IO 2
.SH NAME
enable_io \- (i386) enable access to I/O space
.SH SYNOPSIS
.B #include <sys/syscall.h>
.br
.B int enable_io(int low, int high);
.SH DESCRIPTION
The
.I enable_io()
system call enables access for a thread to use the i386 architecture
I/O instructions.  The process must have
.I sys
privileges.  Once granted, privileges remain for the life of the
thread.  Successive calls are cumulative.
