.TH ENABLE_ISR 2
.SH NAME
enable_isr \- (i386) connect an interrupt vector to a port
.SH SYNOPSIS
.B #include <sys/syscall.h>
.br
.B int enable_isr(port_t port, int irq);
.SH DESCRIPTION
The
.I enable_isr()
system call connects an interrupt level to the specified
port.  After this call, the
.I port
is no longer available to the process, although it remains open
to the corresponding server.  An occurence of an interrupt at
.I irq
level will send an
.I M_ISR.
message to the server.
If this message is not yet received by the server, the
.I m_arg1
field will be incremented by one instead.  Thus, at
most only one
message for the given
.I irq
will ever exist.
.PP
The process must have
.I sys
privileges.  Once granted, the IRQ handling remains until
the server closes the connection.
