.TH EXIT 2
.SH NAME
exit \- terminate current thread
.SH SYNOPSIS
.B #include <std.h>
.br
.B int exit(int status);
.SH DESCRIPTION
The
.I exit()
system call causes the current thread to terminate.
If it is the last thread in the given process, the
process itself terminates.  Process termination generally
results in a status structure being queued to a
parent process; see
.I waits(2).
