.TH MSG_PORT 2
.SH NAME
msg_port \- create a server port
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B int msg_port(port_name pn, port_name *pnp);
.SH DESCRIPTION
The
.I msg_port()
system service creates a new server port.  The
.I pn
parameter provides a system-wide name for the port, and
is passed to
.I msg_connect()
in clients wishing to connect to this server port.
It is an error to use a
.I pn
value already in use on the system.
If zero, a value is picked by the kernel.
.I pnp,
if non-NULL, will be assigned the port name assigned
to the new port.
