.TH MSG_ERR 2
.SH NAME
msg_err \- send back an error
.SH SYNOPSIS
.B #include <sys/msg.h>
.br
.B int msg_err(long sender, char *errstring);
.SH DESCRIPTION
.I msg_err()
is used to return an error from a server to a client.  Most
commonly, it is used to reply with error to a request
received via
.I msg_receive().
The client sees his
.I msg_send()
return a -1, and can access the
.I errstring
by calling
.I strerror().
.PP
The client's connection remains functional, and a new
request can be sent via a new
.I msg_send()
call.
