.TH PAGE_WIRE 2
.SH NAME
page_wire \- lock down pages to physical memory
.SH SYNOPSIS
.B #include <sys/syscall.h>
.br
.B int page_wire(void *vaddr, void **paddr);
.SH DESCRIPTION
The
.I page_wire()
system call
locks a virtual page's contents down to a physical page,
whose corresponding physical address is placed in the location
pointed to by
.I paddr.
.PP
The return value is either -1, indicating failure, or a
.I handle
used in a later call to
.I page_release().
.SH NOTES
This call is generally useful only to DMA-based I/O servers.
