.TH TFORK 2
.SH NAME
tfork \- create new thread under current process
.SH SYNOPSIS
.B #include <std.h>
.br
.B pid_t tfork(voidfun startfun, ulong arg);
.SH DESCRIPTION
.I tfork()
creates a new thread running under the current process.
A thread, unlike a process, shares the address space, permissions,
and open files with all other threads of the current process.
.PP
A thread starts running at the function pointed to by the
.I startfun
argument to
.I tfork();
this function is entered with the single argument
.I arg
available.  This function should not return to its "caller";
.I exit(2)
should be used when the thread wishes to complete.
.PP
.I tfork()'s
return value is the thread
process ID of the new thread.  Note that a thread process
ID is local to the PID of the containing process; see
.I notify(2)
for an example of selecting a thread within a process.
