.TH WAITS 2
.SH NAME
waits \- retrieve status on exiting processes
.SH SYNOPSIS
.nf
.B #include <sys/wait.h>
.B int exit(struct exitst *w, int block_ok);
.PP
struct exitst {
	pid_t e_pid;		/* PID of exit() */
	int e_code;		/* Argument to exit() */
	ulong e_usr, e_sys;	/* CPU time in user and sys */
	struct exitst *e_next;	/* Next in list */
	char e_event[ERRLEN];	/* Name of event if killed */
};
.fi
.SH DESCRIPTION
.I waits()
retrieves status on children processes of the current
process.  Such status is queued during the process of
a child exiting, and includes information on PID,
any argument to
.I exit(),
CPU time used, and the name of the event which caused
process terminating (if any).
.SH SEE ALSO
.I exit(2)
